"""Package wrapper for model definitions."""

from .alignment_batch import AlignmentBatch, AlignmentBatchConfig, AlignmentEpisodeRecord
from .errors import (
    AdriftError,
    AlignmentError,
    BotDetectionError,
    CacheError,
    DownloadError,
    FetchError,
    PipelineError,
    StorageError,
)
from .metadata import (
    DEVICE,
    PROJECT,
    CacheMetadata,
    MediaMetadata,
    RssChannel,
    RssEpisode,
    S3Metadata,
    YtDlpParams,
)
from .output import EpisodeData, PodcastFeed
from .pipeline import (
    DownloadEpisode,
    MatchCandidateTrace,
    MergeResult,
    ReferenceMatchTrace,
    SourceTrace,
)
from .podcast_config import (
    AlignmentConfig,
    FeedSource,
    PodcastConfig,
    PodcastConfigInput,
    PodcastsTomlConfig,
    ScoringWeights,
    SourceFilter,
    compile_podcast_toml_schema,
    ensure_feed_source,
    ensure_podcast_config,
    ensure_source_filter,
    parse_podcasts_raw,
    podcast_toml_json_schema,
)
from .sponsorblock import SponsorSegment
from .stage_result import StageResult
from .ytdlp import YtDlpImage, YtDlpVideo

__all__ = [
    "DEVICE",
    "PROJECT",
    "AdriftError",
    "AlignmentBatch",
    "AlignmentBatchConfig",
    "AlignmentConfig",
    "AlignmentEpisodeRecord",
    "AlignmentError",
    "BotDetectionError",
    "CacheError",
    "CacheMetadata",
    "DownloadEpisode",
    "DownloadError",
    "EpisodeData",
    "FeedSource",
    "FetchError",
    "MatchCandidateTrace",
    "MediaMetadata",
    "MergeResult",
    "PipelineError",
    "PodcastConfig",
    "PodcastConfigInput",
    "PodcastFeed",
    "PodcastsTomlConfig",
    "ReferenceMatchTrace",
    "RssChannel",
    "RssEpisode",
    "S3Metadata",
    "ScoringWeights",
    "SourceFilter",
    "SourceTrace",
    "SponsorSegment",
    "StageResult",
    "StorageError",
    "YtDlpImage",
    "YtDlpParams",
    "YtDlpVideo",
    "compile_podcast_toml_schema",
    "ensure_feed_source",
    "ensure_podcast_config",
    "ensure_source_filter",
    "parse_podcasts_raw",
    "podcast_toml_json_schema",
]
