from typing import Any, Optional

class Cache:
    def __init__(self, directory: Optional[str] = ..., size_limit: Optional[int] = ...) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def set(self, key: str, value: Any, expire: Optional[int] = ...) -> None: ...
    def delete(self, key: str) -> None: ...
    def clear(self) -> None: ...
