from typing import Iterator, TypeVar, Union

_T = TypeVar("_T", int, float)

class Atomic:
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    @property
    def left(self) -> int: ...  # CLOSED or OPEN
    @property
    def right(self) -> int: ...  # CLOSED or OPEN

class Interval:
    def __or__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __ior__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __and__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __iand__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __sub__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __isub__(self, other: Union[Interval, Atomic]) -> Interval: ...
    def __iter__(self) -> Iterator[Atomic]: ...
    def __contains__(self, item: float) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    @property
    def atomic(self) -> bool: ...
    @property
    def enclosure(self) -> Atomic: ...

def empty() -> Interval: ...
def open(lower: _T, upper: _T) -> Interval: ...
def closed(lower: _T, upper: _T) -> Interval: ...
def openclosed(lower: _T, upper: _T) -> Interval: ...
def closedopen(lower: _T, upper: _T) -> Interval: ...
def singleton(value: _T) -> Interval: ...

CLOSED: int
OPEN: int
