from pathlib import Path as _Path
from typing import Any, Callable, Tuple

class MonkeyPatch:
    def setattr(self, target: object, name: str, value: object, raising: bool = True) -> None: ...
    def setenv(self, name: str, value: str) -> None: ...
    def delenv(self, name: str, raising: bool = False) -> None: ...

class CaptureFixture:
    def readouterr(self) -> Tuple[str, str]: ...

def fixture(func: Callable[..., Any]) -> Callable[..., Any]: ...

class TempPathFactory:
    def mktemp(self, basename: str) -> _Path: ...
