from typing import Any, Optional, Callable

class Stream:
    def download(
        self, output_path: Optional[str] = ..., filename: Optional[str] = ...
    ) -> str: ...

class StreamQuery:
    def filter(self, *args: Any, **kwargs: Any) -> "StreamQuery": ...
    def order_by(self, key: str) -> "StreamQuery": ...
    def desc(self) -> "StreamQuery": ...
    def first(self) -> Optional[Stream]: ...

class YouTube:
    def __init__(
        self, url: str, on_callback: Optional[Callable[..., Any]] = ...
    ) -> None: ...
    title: str
    id: str
    age_restricted: bool
    streams: StreamQuery

def on_progress(stream: Any, chunk: bytes, bytes_remaining: int) -> None: ...
