from typing import Any, Tuple

class _PILImage:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def convert(self, *args: Any, **kwargs: Any) -> "_PILImage": ...
    def resize(self, *args: Any, **kwargs: Any) -> "_PILImage": ...
    def crop(self, *args: Any, **kwargs: Any) -> "_PILImage": ...
    def thumbnail(self, *args: Any, **kwargs: Any) -> None: ...
    def paste(self, *args: Any, **kwargs: Any) -> None: ...
    mode: str
    size: Tuple[int, int]
    width: int
    height: int
    def __enter__(self) -> "_PILImage": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...


class _ImageModule:
    Image: type[_PILImage]
    Resampling: Any
    LANCZOS: Any
    def open(self, *args: Any, **kwargs: Any) -> _PILImage: ...
    def new(self, *args: Any, **kwargs: Any) -> _PILImage: ...


Image: _ImageModule
